#!/bin/sh

#############################################################
#                  Hi3798mv200 RS485 Setup                  #
#  author     :  utlark                                     #
#  date       :  2022.08.13                                 #
#  ver        :  1.0                                        #
#############################################################

########## Baseaddr            0xf8a21000           #########
#############################################################
#  Function            GPIO      IO    Offset    Value      #
#  485 CTSN           GPIO2_3    19    0x04C   0x00000132   #
#  485 RTSN           GPIO2_4    20    0x050   0x00000132   #
#  485 RX             GPIO2_5    21    0x054   0x00000132   #
#  485 TX             GPIO2_6    22    0x058   0x00000132   #
#############################################################

devmem 0XF8A2104C w 0x00000130
devmem 0XF8A21050 w 0x00000130
devmem 0XF8A21054 w 0x00000132
devmem 0XF8A21058 w 0x00000132

echo 19  > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio19/direction
echo 0   > /sys/class/gpio/gpio19/value

stty -F /dev/ttyAMA2 speed 115200 > /dev/null

