#!/bin/sh
#
# Load hisilicon kernel module...
#

case "$1" in
  start)
    cd /kmod
    ./load
    ;;
  stop)
    cd /kmod
    ./unload
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

