#!/bin/sh
#
# Setup RS485 to input...
#

case "$1" in
  start)
    echo "Setup RS485 to input..."
    source /etc/profile

    /etc/network/setup-rs485-input
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

