#!/bin/sh

# Sort of APIPA 
for i in 1 2 3 4 5 6 7 8 9 10
do
    sleep 0.$((RANDOM % 50))
    temp_ip=$((i + 200))
    ifconfig eth0:0 169.254.200.$temp_ip netmask 255.255.0.0
    if ping -c1 -w3 169.254.200.$i > /dev/null 2>&1
    then
        ifconfig eth0:0 0.0.0.0
    else
        ifconfig eth0:0 169.254.200.$i netmask 255.255.0.0
        route add default gw 169.254.0.1
        static_ip="yes"
        break
    fi
done

if [ -z "$static_ip" ]
then
    echo "~recovery-network~ static addresses 169.254.200.[1-10] are occupied by another devices"
fi
