#!/bin/sh
#
# Setup USB Hub...
#

case "$1" in
  start)
    echo "Setup USB Hub..."
    source /etc/profile

    sh /etc/udev/hub-rebind &
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

