#!/bin/sh
#
# Setup USB Hub...
#

case "$1" in
  start)
    echo "Setup USB Hub..."
    source /etc/profile

    if [ -d /sys/bus/usb/drivers/hub/1-1:1.0 ]
    then
        echo '1-1:1.0' > /sys/bus/usb/drivers/hub/unbind
        echo '1-1:1.0' > /sys/bus/usb/drivers/hub/bind
    fi
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

