#!/bin/sh
#
# Setup time from fake RTC...
#

case "$1" in
  start)
    echo "Setup time from fake RTC..."
    source /etc/profile

    sh /etc/rtc/outer-rtc.sh setLinux &
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

