#!/bin/sh

case "$1" in
  start)
    echo "Starting network configuration script..."
    source /etc/profile

    ifconfig eth0:0 169.254.200.1 netmask 255.255.0.0
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

