#!/bin/sh

case "$1" in
  start)
 	echo "Starting network configuration script..."
	source /etc/profile

	cd /etc/network
	sh ./recovery-network &
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

